#cloud-config

name: k3s server
hostname: server-{{ trunc 4 .MachineID }}

install:
  device: /dev/sda
  reboot: true
  auto: true

users:
  - name: kairos
    passwd: kairos
    groups:
      - admin
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMR46OCN8sSx05VPui+gCDXX+O8VkeIctfOkS9rlKwIh # public key

k3s:
  enabled: true
  args:
    - --server "https://192.168.0.100:6443"
    - --tls-san "192.168.0.100"
    - --node-label "role=control-plane"
  env:
    K3S_TOKEN: "66e9544845135293dad82e855886198a"
    K3S_URL: "https://192.168.0.100:6443"
